enum PairEnum {
  AUDUSD,AUDCAD,AUDJPY,AUDCHF,AUDNZD,CADCHF,CADJPY,CHFJPY,EURAUD,EURCAD,
  EURCHF,EURGBP,EURJPY,EURNZD,EURUSD,GBPAUD,GBPCAD,GBPCHF,GBPJPY,GBPNZD,
  GBPUSD,NZDCAD,NZDCHF,NZDJPY,NZDUSD,USDCAD,USDCHF,USDJPY,XAUUSD
}